### ISSUE TITLE
Need OISST data for MLR predictor

### ISSUE THREAD

**Issue by danielharnos** [noaa-nws-cpc/realtime-oni#6]
The 90-day ONI is used for the MLR and Phase Model to determine the skill backdrop, and for the Phase Model is the ENSO predictor. For the MLR the ENSO predictor is the 2-week running mean Nino 3.4 SST anomaly from OISSTv2. Can I get either 14-day running mean anomalies or daily anomalies for ingest into my process?

Thanks in advance!

**Comment by adamallgood** [comment]
The coding work for this feature is done, and a NCO RFC is in for a planned update to the ops version on July 3, 2018. Edits to the docs are still needed to reflect the expanded work done by the daily ONI calculator script. WIll close this ticket once that is done.

**Comment by adamallgood** [comment]
Documentation is updated, and this feature is ready to be deployed into ops (will be version 1.02). See noaa-nws-cpc/compute-farm-ops#1006 for progress on that deployment. Closing ticket.

**Comment by adamallgood** [comment]
Deployed in ops. See noaa-nws-cpc/compute-farm-ops#1006
