### ISSUE TITLE
Output from update-daily-oni-archive.pl alls says 90 days

### ISSUE THREAD

**Issue by adamallgood** [noaa-nws-cpc/realtime-oni#7]
See comment from @danielharnos in noaa-nws-cpc/compute-farm-ops#1006

**Comment by danielharnos** [comment]
Git er done!

**Comment by adamallgood** [comment]
@danielharnos - See /cpc/home/aallgood/data/observations/ocean/long_range/global/oni-avhrr/2018/oni-1day-ending-20180628.txt and /cpc/home/aallgood/data/observations/ocean/long_range/global/oni-avhrr/2018/oni-14day-ending-20180628.txt - the bug is fixed.

**Comment by adamallgood** [comment]
Deployed in ops. See noaa-nws-cpc/compute-farm-ops#1006
